### ISSUE TITLE
Error out with ncsim

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/lake#17]
As of a89c091, the top test errors out with ncsim, but passes with Verilator. I'm suspecting it's `x` related issue since Verilator doesn't handle `x`. It could also be timing/cycle related bug.

**Comment by mbstrange2** [comment]
Commit fixes this - just needed to add `zero_inputs()` to fault benches - https://github.com/StanfordAHA/lake/commit/48c4b763ecfd3464f6c6679c3991cd3945d57f39
