### ISSUE TITLE
Chaining logic needs disable

### ISSUE THREAD

**Issue by mbstrange2** [StanfordAHA/lake#36]
We need to properly disable chaining for single tile apps.

Requesting test for @Kuree

**Comment by kavyasreedhar** [comment]
Fixed and pushed to Lake + garnet.

**Comment by Kuree** [comment]
@kavyasreedhar Can you create a unit test here as part of regression test?

**Comment by kavyasreedhar** [comment]
@Kuree Sounds good, I will add it to the Lake repo.

**Comment by kavyasreedhar** [comment]
I think this is deprecated...
