### ISSUE TITLE
Create a chain of and gate use reduce in Kratos

### ISSUE THREAD

**Issue by joyliu37** [StanfordAHA/lake#41]
I am trying to use kratos to generate the accessor hardware. 

This combinational logic in `piece_sel` [function](https://github.com/StanfordAHA/lake/blob/e9c2dc81a27c59a9de5bf2839f2a09d8289225d7/lake/spec/basic.py#L70-L77) is to "and" a bunch of bool variables produced by the comparison logic. And doing a log operation on it. I get the following error when run this hardware generator. Could any Kratos expert told me which part I wrote is incorrect? 

 File "basic.py", line 65, in __init__
    self.add_code(self.piece_sel)
  File "/nobackup/joeyliu/aha/lakeenv/lib/python3.7/site-packages/kratos/generator.py", line 558, in add_always
    fn_ln, kargs)
  File "/nobackup/joeyliu/aha/lakeenv/lib/python3.7/site-packages/kratos/pyast.py", line 848, in transform_stmt_block
    exec(code_obj, _globals)
  File "<ast>", line 10, in <module>
  File "<ast>", line 5, in piece_sel
  File "<ast>", line 5, in <listcomp>
_kratos.exception.InvalidConversionException: Cannot convert a variable to bool

**Comment by Kuree** [comment]
Use `reduce_and` and change `and` to `&`. Python doesn't allow you to overload `and` operator.

**Comment by joyliu37** [comment]
Should I change it to
`reduce(lambda a, b: a & b, [(self._iter[j] >= self._lb_arr[j]) & (self._iter[j] <= self._ub_arr[j]) \
                                             for j in range(self.input_dim)])`
It still gives me the same error.
